# golangci-lint configuration for Terraform Provider for OSD on Google Cloud
# https://golangci-lint.run/usage/configuration/
version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  govet:
    enable:
      - shadow

issues:
  exclude-dirs:
    - references
    - reference
    - subsystem
    - acceptance
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
