// Code generated by MockGen. DO NOT EDIT.
// Source: cluster_waiter.go
//
// Generated by this command:
//
//	mockgen -source=cluster_waiter.go -package=common -destination=cluster_waiter_mock.go
//
// Package common is a generated GoMock package.
package common

import (
	context "context"
	reflect "reflect"

	v1 "github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockClusterWait is a mock of ClusterWait interface.
type MockClusterWait struct {
	ctrl     *gomock.Controller
	recorder *MockClusterWaitMockRecorder
}

// MockClusterWaitMockRecorder is the mock recorder for MockClusterWait.
type MockClusterWaitMockRecorder struct {
	mock *MockClusterWait
}

// NewMockClusterWait creates a new mock instance.
func NewMockClusterWait(ctrl *gomock.Controller) *MockClusterWait {
	mock := &MockClusterWait{ctrl: ctrl}
	mock.recorder = &MockClusterWaitMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterWait) EXPECT() *MockClusterWaitMockRecorder {
	return m.recorder
}

// WaitForClusterToBeDeleted mocks base method.
func (m *MockClusterWait) WaitForClusterToBeDeleted(ctx context.Context, clusterID string, waitTimeoutMin int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForClusterToBeDeleted", ctx, clusterID, waitTimeoutMin)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForClusterToBeDeleted indicates an expected call of WaitForClusterToBeDeleted.
func (mr *MockClusterWaitMockRecorder) WaitForClusterToBeDeleted(ctx, clusterID, waitTimeoutMin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForClusterToBeDeleted", reflect.TypeOf((*MockClusterWait)(nil).WaitForClusterToBeDeleted), ctx, clusterID, waitTimeoutMin)
}

// WaitForClusterToBeReady mocks base method.
func (m *MockClusterWait) WaitForClusterToBeReady(ctx context.Context, clusterID string, waitTimeoutMin int64) (*v1.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForClusterToBeReady", ctx, clusterID, waitTimeoutMin)
	ret0, _ := ret[0].(*v1.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitForClusterToBeReady indicates an expected call of WaitForClusterToBeReady.
func (mr *MockClusterWaitMockRecorder) WaitForClusterToBeReady(ctx, clusterID, waitTimeoutMin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForClusterToBeReady", reflect.TypeOf((*MockClusterWait)(nil).WaitForClusterToBeReady), ctx, clusterID, waitTimeoutMin)
}
